/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVarianteRouteImport } from './routes/_app.variante'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppTimeLogRouteImport } from './routes/_app.time-log'
import { Route as AppTabelaCorRouteImport } from './routes/_app.tabela-cor'
import { Route as AppSenhaRouteImport } from './routes/_app.senha'
import { Route as AppRepresentantesRouteImport } from './routes/_app.representantes'
import { Route as AppRepMetaRouteImport } from './routes/_app.rep-meta'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppMenusRouteImport } from './routes/_app.menus'
import { Route as AppMaquinaRouteImport } from './routes/_app.maquina'
import { Route as AppLotesRouteImport } from './routes/_app.lotes'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppFuncionarioRouteImport } from './routes/_app.funcionario'
import { Route as AppFioRouteImport } from './routes/_app.fio'
import { Route as AppEstoqueTecidosRouteImport } from './routes/_app.estoque-tecidos'
import { Route as AppEstoqueFiosRouteImport } from './routes/_app.estoque-fios'
import { Route as AppEstampaRouteImport } from './routes/_app.estampa'
import { Route as AppEmpresaRouteImport } from './routes/_app.empresa'
import { Route as AppCorreiaRouteImport } from './routes/_app.correia'
import { Route as AppCorRouteImport } from './routes/_app.cor'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComposicaoRouteImport } from './routes/_app.composicao'
import { Route as AppClienteArtigoRouteImport } from './routes/_app.cliente-artigo'
import { Route as AppArtigosRouteImport } from './routes/_app.artigos'
import { Route as AppAgulhaRouteImport } from './routes/_app.agulha'
import { Route as AppProducaoIndexRouteImport } from './routes/_app.producao.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/_app.financeiro.index'
import { Route as AppProducaoQualidadeRouteImport } from './routes/_app.producao.qualidade'
import { Route as AppProducaoPedidosRouteImport } from './routes/_app.producao.pedidos'
import { Route as AppProducaoOpRouteImport } from './routes/_app.producao.op'
import { Route as AppProducaoExpedicaoRouteImport } from './routes/_app.producao.expedicao'
import { Route as AppFiscalUfIcmsRouteImport } from './routes/_app.fiscal.uf-icms'
import { Route as AppFiscalRNotaFiscalRouteImport } from './routes/_app.fiscal.r-nota-fiscal'
import { Route as AppFiscalNotaFiscalUploadRouteImport } from './routes/_app.fiscal.nota-fiscal-upload'
import { Route as AppFiscalNotaFiscalImportacaoRouteImport } from './routes/_app.fiscal.nota-fiscal-importacao'
import { Route as AppFiscalNotaFiscalRouteImport } from './routes/_app.fiscal.nota-fiscal'
import { Route as AppFiscalImpostosRouteImport } from './routes/_app.fiscal.impostos'
import { Route as AppFiscalDashboardRouteImport } from './routes/_app.fiscal.dashboard'
import { Route as AppFiscalCfopRouteImport } from './routes/_app.fiscal.cfop'
import { Route as AppFiscalCertificadosRouteImport } from './routes/_app.fiscal.certificados'
import { Route as AppDevCargosRouteImport } from './routes/_app.dev.cargos'
import { Route as AppDashboardIndustrialRouteImport } from './routes/_app.dashboard.industrial'
import { Route as AppProducaoOpIdRouteImport } from './routes/_app.producao.op.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVarianteRoute = AppVarianteRouteImport.update({
  id: '/variante',
  path: '/variante',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeLogRoute = AppTimeLogRouteImport.update({
  id: '/time-log',
  path: '/time-log',
  getParentRoute: () => AppRoute,
} as any)
const AppTabelaCorRoute = AppTabelaCorRouteImport.update({
  id: '/tabela-cor',
  path: '/tabela-cor',
  getParentRoute: () => AppRoute,
} as any)
const AppSenhaRoute = AppSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AppRoute,
} as any)
const AppRepresentantesRoute = AppRepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => AppRoute,
} as any)
const AppRepMetaRoute = AppRepMetaRouteImport.update({
  id: '/rep-meta',
  path: '/rep-meta',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppMaquinaRoute = AppMaquinaRouteImport.update({
  id: '/maquina',
  path: '/maquina',
  getParentRoute: () => AppRoute,
} as any)
const AppLotesRoute = AppLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionarioRoute = AppFuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => AppRoute,
} as any)
const AppFioRoute = AppFioRouteImport.update({
  id: '/fio',
  path: '/fio',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueTecidosRoute = AppEstoqueTecidosRouteImport.update({
  id: '/estoque-tecidos',
  path: '/estoque-tecidos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueFiosRoute = AppEstoqueFiosRouteImport.update({
  id: '/estoque-fios',
  path: '/estoque-fios',
  getParentRoute: () => AppRoute,
} as any)
const AppEstampaRoute = AppEstampaRouteImport.update({
  id: '/estampa',
  path: '/estampa',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppCorreiaRoute = AppCorreiaRouteImport.update({
  id: '/correia',
  path: '/correia',
  getParentRoute: () => AppRoute,
} as any)
const AppCorRoute = AppCorRouteImport.update({
  id: '/cor',
  path: '/cor',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComposicaoRoute = AppComposicaoRouteImport.update({
  id: '/composicao',
  path: '/composicao',
  getParentRoute: () => AppRoute,
} as any)
const AppClienteArtigoRoute = AppClienteArtigoRouteImport.update({
  id: '/cliente-artigo',
  path: '/cliente-artigo',
  getParentRoute: () => AppRoute,
} as any)
const AppArtigosRoute = AppArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgulhaRoute = AppAgulhaRouteImport.update({
  id: '/agulha',
  path: '/agulha',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoIndexRoute = AppProducaoIndexRouteImport.update({
  id: '/producao/',
  path: '/producao/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoQualidadeRoute = AppProducaoQualidadeRouteImport.update({
  id: '/producao/qualidade',
  path: '/producao/qualidade',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoPedidosRoute = AppProducaoPedidosRouteImport.update({
  id: '/producao/pedidos',
  path: '/producao/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoOpRoute = AppProducaoOpRouteImport.update({
  id: '/producao/op',
  path: '/producao/op',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoExpedicaoRoute = AppProducaoExpedicaoRouteImport.update({
  id: '/producao/expedicao',
  path: '/producao/expedicao',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalUfIcmsRoute = AppFiscalUfIcmsRouteImport.update({
  id: '/fiscal/uf-icms',
  path: '/fiscal/uf-icms',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalRNotaFiscalRoute = AppFiscalRNotaFiscalRouteImport.update({
  id: '/fiscal/r-nota-fiscal',
  path: '/fiscal/r-nota-fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalNotaFiscalUploadRoute =
  AppFiscalNotaFiscalUploadRouteImport.update({
    id: '/fiscal/nota-fiscal-upload',
    path: '/fiscal/nota-fiscal-upload',
    getParentRoute: () => AppRoute,
  } as any)
const AppFiscalNotaFiscalImportacaoRoute =
  AppFiscalNotaFiscalImportacaoRouteImport.update({
    id: '/fiscal/nota-fiscal-importacao',
    path: '/fiscal/nota-fiscal-importacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppFiscalNotaFiscalRoute = AppFiscalNotaFiscalRouteImport.update({
  id: '/fiscal/nota-fiscal',
  path: '/fiscal/nota-fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalImpostosRoute = AppFiscalImpostosRouteImport.update({
  id: '/fiscal/impostos',
  path: '/fiscal/impostos',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalDashboardRoute = AppFiscalDashboardRouteImport.update({
  id: '/fiscal/dashboard',
  path: '/fiscal/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalCfopRoute = AppFiscalCfopRouteImport.update({
  id: '/fiscal/cfop',
  path: '/fiscal/cfop',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalCertificadosRoute = AppFiscalCertificadosRouteImport.update({
  id: '/fiscal/certificados',
  path: '/fiscal/certificados',
  getParentRoute: () => AppRoute,
} as any)
const AppDevCargosRoute = AppDevCargosRouteImport.update({
  id: '/dev/cargos',
  path: '/dev/cargos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndustrialRoute = AppDashboardIndustrialRouteImport.update({
  id: '/dashboard/industrial',
  path: '/dashboard/industrial',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoOpIdRoute = AppProducaoOpIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProducaoOpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/agulha': typeof AppAgulhaRoute
  '/artigos': typeof AppArtigosRoute
  '/cliente-artigo': typeof AppClienteArtigoRoute
  '/composicao': typeof AppComposicaoRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cor': typeof AppCorRoute
  '/correia': typeof AppCorreiaRoute
  '/empresa': typeof AppEmpresaRoute
  '/estampa': typeof AppEstampaRoute
  '/estoque-fios': typeof AppEstoqueFiosRoute
  '/estoque-tecidos': typeof AppEstoqueTecidosRoute
  '/fio': typeof AppFioRoute
  '/funcionario': typeof AppFuncionarioRoute
  '/inicio': typeof AppInicioRoute
  '/lotes': typeof AppLotesRoute
  '/maquina': typeof AppMaquinaRoute
  '/menus': typeof AppMenusRoute
  '/produtos': typeof AppProdutosRoute
  '/rep-meta': typeof AppRepMetaRoute
  '/representantes': typeof AppRepresentantesRoute
  '/senha': typeof AppSenhaRoute
  '/tabela-cor': typeof AppTabelaCorRoute
  '/time-log': typeof AppTimeLogRoute
  '/usuarios': typeof AppUsuariosRoute
  '/variante': typeof AppVarianteRoute
  '/dashboard/industrial': typeof AppDashboardIndustrialRoute
  '/dev/cargos': typeof AppDevCargosRoute
  '/fiscal/certificados': typeof AppFiscalCertificadosRoute
  '/fiscal/cfop': typeof AppFiscalCfopRoute
  '/fiscal/dashboard': typeof AppFiscalDashboardRoute
  '/fiscal/impostos': typeof AppFiscalImpostosRoute
  '/fiscal/nota-fiscal': typeof AppFiscalNotaFiscalRoute
  '/fiscal/nota-fiscal-importacao': typeof AppFiscalNotaFiscalImportacaoRoute
  '/fiscal/nota-fiscal-upload': typeof AppFiscalNotaFiscalUploadRoute
  '/fiscal/r-nota-fiscal': typeof AppFiscalRNotaFiscalRoute
  '/fiscal/uf-icms': typeof AppFiscalUfIcmsRoute
  '/producao/expedicao': typeof AppProducaoExpedicaoRoute
  '/producao/op': typeof AppProducaoOpRouteWithChildren
  '/producao/pedidos': typeof AppProducaoPedidosRoute
  '/producao/qualidade': typeof AppProducaoQualidadeRoute
  '/financeiro/': typeof AppFinanceiroIndexRoute
  '/producao/': typeof AppProducaoIndexRoute
  '/producao/op/$id': typeof AppProducaoOpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/agulha': typeof AppAgulhaRoute
  '/artigos': typeof AppArtigosRoute
  '/cliente-artigo': typeof AppClienteArtigoRoute
  '/composicao': typeof AppComposicaoRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cor': typeof AppCorRoute
  '/correia': typeof AppCorreiaRoute
  '/empresa': typeof AppEmpresaRoute
  '/estampa': typeof AppEstampaRoute
  '/estoque-fios': typeof AppEstoqueFiosRoute
  '/estoque-tecidos': typeof AppEstoqueTecidosRoute
  '/fio': typeof AppFioRoute
  '/funcionario': typeof AppFuncionarioRoute
  '/inicio': typeof AppInicioRoute
  '/lotes': typeof AppLotesRoute
  '/maquina': typeof AppMaquinaRoute
  '/menus': typeof AppMenusRoute
  '/produtos': typeof AppProdutosRoute
  '/rep-meta': typeof AppRepMetaRoute
  '/representantes': typeof AppRepresentantesRoute
  '/senha': typeof AppSenhaRoute
  '/tabela-cor': typeof AppTabelaCorRoute
  '/time-log': typeof AppTimeLogRoute
  '/usuarios': typeof AppUsuariosRoute
  '/variante': typeof AppVarianteRoute
  '/dashboard/industrial': typeof AppDashboardIndustrialRoute
  '/dev/cargos': typeof AppDevCargosRoute
  '/fiscal/certificados': typeof AppFiscalCertificadosRoute
  '/fiscal/cfop': typeof AppFiscalCfopRoute
  '/fiscal/dashboard': typeof AppFiscalDashboardRoute
  '/fiscal/impostos': typeof AppFiscalImpostosRoute
  '/fiscal/nota-fiscal': typeof AppFiscalNotaFiscalRoute
  '/fiscal/nota-fiscal-importacao': typeof AppFiscalNotaFiscalImportacaoRoute
  '/fiscal/nota-fiscal-upload': typeof AppFiscalNotaFiscalUploadRoute
  '/fiscal/r-nota-fiscal': typeof AppFiscalRNotaFiscalRoute
  '/fiscal/uf-icms': typeof AppFiscalUfIcmsRoute
  '/producao/expedicao': typeof AppProducaoExpedicaoRoute
  '/producao/op': typeof AppProducaoOpRouteWithChildren
  '/producao/pedidos': typeof AppProducaoPedidosRoute
  '/producao/qualidade': typeof AppProducaoQualidadeRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/producao': typeof AppProducaoIndexRoute
  '/producao/op/$id': typeof AppProducaoOpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_app/agulha': typeof AppAgulhaRoute
  '/_app/artigos': typeof AppArtigosRoute
  '/_app/cliente-artigo': typeof AppClienteArtigoRoute
  '/_app/composicao': typeof AppComposicaoRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/cor': typeof AppCorRoute
  '/_app/correia': typeof AppCorreiaRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/estampa': typeof AppEstampaRoute
  '/_app/estoque-fios': typeof AppEstoqueFiosRoute
  '/_app/estoque-tecidos': typeof AppEstoqueTecidosRoute
  '/_app/fio': typeof AppFioRoute
  '/_app/funcionario': typeof AppFuncionarioRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/lotes': typeof AppLotesRoute
  '/_app/maquina': typeof AppMaquinaRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/rep-meta': typeof AppRepMetaRoute
  '/_app/representantes': typeof AppRepresentantesRoute
  '/_app/senha': typeof AppSenhaRoute
  '/_app/tabela-cor': typeof AppTabelaCorRoute
  '/_app/time-log': typeof AppTimeLogRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/variante': typeof AppVarianteRoute
  '/_app/dashboard/industrial': typeof AppDashboardIndustrialRoute
  '/_app/dev/cargos': typeof AppDevCargosRoute
  '/_app/fiscal/certificados': typeof AppFiscalCertificadosRoute
  '/_app/fiscal/cfop': typeof AppFiscalCfopRoute
  '/_app/fiscal/dashboard': typeof AppFiscalDashboardRoute
  '/_app/fiscal/impostos': typeof AppFiscalImpostosRoute
  '/_app/fiscal/nota-fiscal': typeof AppFiscalNotaFiscalRoute
  '/_app/fiscal/nota-fiscal-importacao': typeof AppFiscalNotaFiscalImportacaoRoute
  '/_app/fiscal/nota-fiscal-upload': typeof AppFiscalNotaFiscalUploadRoute
  '/_app/fiscal/r-nota-fiscal': typeof AppFiscalRNotaFiscalRoute
  '/_app/fiscal/uf-icms': typeof AppFiscalUfIcmsRoute
  '/_app/producao/expedicao': typeof AppProducaoExpedicaoRoute
  '/_app/producao/op': typeof AppProducaoOpRouteWithChildren
  '/_app/producao/pedidos': typeof AppProducaoPedidosRoute
  '/_app/producao/qualidade': typeof AppProducaoQualidadeRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/producao/': typeof AppProducaoIndexRoute
  '/_app/producao/op/$id': typeof AppProducaoOpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/agulha'
    | '/artigos'
    | '/cliente-artigo'
    | '/composicao'
    | '/configuracoes'
    | '/cor'
    | '/correia'
    | '/empresa'
    | '/estampa'
    | '/estoque-fios'
    | '/estoque-tecidos'
    | '/fio'
    | '/funcionario'
    | '/inicio'
    | '/lotes'
    | '/maquina'
    | '/menus'
    | '/produtos'
    | '/rep-meta'
    | '/representantes'
    | '/senha'
    | '/tabela-cor'
    | '/time-log'
    | '/usuarios'
    | '/variante'
    | '/dashboard/industrial'
    | '/dev/cargos'
    | '/fiscal/certificados'
    | '/fiscal/cfop'
    | '/fiscal/dashboard'
    | '/fiscal/impostos'
    | '/fiscal/nota-fiscal'
    | '/fiscal/nota-fiscal-importacao'
    | '/fiscal/nota-fiscal-upload'
    | '/fiscal/r-nota-fiscal'
    | '/fiscal/uf-icms'
    | '/producao/expedicao'
    | '/producao/op'
    | '/producao/pedidos'
    | '/producao/qualidade'
    | '/financeiro/'
    | '/producao/'
    | '/producao/op/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/agulha'
    | '/artigos'
    | '/cliente-artigo'
    | '/composicao'
    | '/configuracoes'
    | '/cor'
    | '/correia'
    | '/empresa'
    | '/estampa'
    | '/estoque-fios'
    | '/estoque-tecidos'
    | '/fio'
    | '/funcionario'
    | '/inicio'
    | '/lotes'
    | '/maquina'
    | '/menus'
    | '/produtos'
    | '/rep-meta'
    | '/representantes'
    | '/senha'
    | '/tabela-cor'
    | '/time-log'
    | '/usuarios'
    | '/variante'
    | '/dashboard/industrial'
    | '/dev/cargos'
    | '/fiscal/certificados'
    | '/fiscal/cfop'
    | '/fiscal/dashboard'
    | '/fiscal/impostos'
    | '/fiscal/nota-fiscal'
    | '/fiscal/nota-fiscal-importacao'
    | '/fiscal/nota-fiscal-upload'
    | '/fiscal/r-nota-fiscal'
    | '/fiscal/uf-icms'
    | '/producao/expedicao'
    | '/producao/op'
    | '/producao/pedidos'
    | '/producao/qualidade'
    | '/financeiro'
    | '/producao'
    | '/producao/op/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/login'
    | '/_app/agulha'
    | '/_app/artigos'
    | '/_app/cliente-artigo'
    | '/_app/composicao'
    | '/_app/configuracoes'
    | '/_app/cor'
    | '/_app/correia'
    | '/_app/empresa'
    | '/_app/estampa'
    | '/_app/estoque-fios'
    | '/_app/estoque-tecidos'
    | '/_app/fio'
    | '/_app/funcionario'
    | '/_app/inicio'
    | '/_app/lotes'
    | '/_app/maquina'
    | '/_app/menus'
    | '/_app/produtos'
    | '/_app/rep-meta'
    | '/_app/representantes'
    | '/_app/senha'
    | '/_app/tabela-cor'
    | '/_app/time-log'
    | '/_app/usuarios'
    | '/_app/variante'
    | '/_app/dashboard/industrial'
    | '/_app/dev/cargos'
    | '/_app/fiscal/certificados'
    | '/_app/fiscal/cfop'
    | '/_app/fiscal/dashboard'
    | '/_app/fiscal/impostos'
    | '/_app/fiscal/nota-fiscal'
    | '/_app/fiscal/nota-fiscal-importacao'
    | '/_app/fiscal/nota-fiscal-upload'
    | '/_app/fiscal/r-nota-fiscal'
    | '/_app/fiscal/uf-icms'
    | '/_app/producao/expedicao'
    | '/_app/producao/op'
    | '/_app/producao/pedidos'
    | '/_app/producao/qualidade'
    | '/_app/financeiro/'
    | '/_app/producao/'
    | '/_app/producao/op/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/variante': {
      id: '/_app/variante'
      path: '/variante'
      fullPath: '/variante'
      preLoaderRoute: typeof AppVarianteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time-log': {
      id: '/_app/time-log'
      path: '/time-log'
      fullPath: '/time-log'
      preLoaderRoute: typeof AppTimeLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tabela-cor': {
      id: '/_app/tabela-cor'
      path: '/tabela-cor'
      fullPath: '/tabela-cor'
      preLoaderRoute: typeof AppTabelaCorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/senha': {
      id: '/_app/senha'
      path: '/senha'
      fullPath: '/senha'
      preLoaderRoute: typeof AppSenhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/representantes': {
      id: '/_app/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof AppRepresentantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rep-meta': {
      id: '/_app/rep-meta'
      path: '/rep-meta'
      fullPath: '/rep-meta'
      preLoaderRoute: typeof AppRepMetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maquina': {
      id: '/_app/maquina'
      path: '/maquina'
      fullPath: '/maquina'
      preLoaderRoute: typeof AppMaquinaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotes': {
      id: '/_app/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AppLotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funcionario': {
      id: '/_app/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof AppFuncionarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fio': {
      id: '/_app/fio'
      path: '/fio'
      fullPath: '/fio'
      preLoaderRoute: typeof AppFioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque-tecidos': {
      id: '/_app/estoque-tecidos'
      path: '/estoque-tecidos'
      fullPath: '/estoque-tecidos'
      preLoaderRoute: typeof AppEstoqueTecidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque-fios': {
      id: '/_app/estoque-fios'
      path: '/estoque-fios'
      fullPath: '/estoque-fios'
      preLoaderRoute: typeof AppEstoqueFiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estampa': {
      id: '/_app/estampa'
      path: '/estampa'
      fullPath: '/estampa'
      preLoaderRoute: typeof AppEstampaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correia': {
      id: '/_app/correia'
      path: '/correia'
      fullPath: '/correia'
      preLoaderRoute: typeof AppCorreiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cor': {
      id: '/_app/cor'
      path: '/cor'
      fullPath: '/cor'
      preLoaderRoute: typeof AppCorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/composicao': {
      id: '/_app/composicao'
      path: '/composicao'
      fullPath: '/composicao'
      preLoaderRoute: typeof AppComposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cliente-artigo': {
      id: '/_app/cliente-artigo'
      path: '/cliente-artigo'
      fullPath: '/cliente-artigo'
      preLoaderRoute: typeof AppClienteArtigoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artigos': {
      id: '/_app/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof AppArtigosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agulha': {
      id: '/_app/agulha'
      path: '/agulha'
      fullPath: '/agulha'
      preLoaderRoute: typeof AppAgulhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/': {
      id: '/_app/producao/'
      path: '/producao'
      fullPath: '/producao/'
      preLoaderRoute: typeof AppProducaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/qualidade': {
      id: '/_app/producao/qualidade'
      path: '/producao/qualidade'
      fullPath: '/producao/qualidade'
      preLoaderRoute: typeof AppProducaoQualidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/pedidos': {
      id: '/_app/producao/pedidos'
      path: '/producao/pedidos'
      fullPath: '/producao/pedidos'
      preLoaderRoute: typeof AppProducaoPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/op': {
      id: '/_app/producao/op'
      path: '/producao/op'
      fullPath: '/producao/op'
      preLoaderRoute: typeof AppProducaoOpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/expedicao': {
      id: '/_app/producao/expedicao'
      path: '/producao/expedicao'
      fullPath: '/producao/expedicao'
      preLoaderRoute: typeof AppProducaoExpedicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/uf-icms': {
      id: '/_app/fiscal/uf-icms'
      path: '/fiscal/uf-icms'
      fullPath: '/fiscal/uf-icms'
      preLoaderRoute: typeof AppFiscalUfIcmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/r-nota-fiscal': {
      id: '/_app/fiscal/r-nota-fiscal'
      path: '/fiscal/r-nota-fiscal'
      fullPath: '/fiscal/r-nota-fiscal'
      preLoaderRoute: typeof AppFiscalRNotaFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/nota-fiscal-upload': {
      id: '/_app/fiscal/nota-fiscal-upload'
      path: '/fiscal/nota-fiscal-upload'
      fullPath: '/fiscal/nota-fiscal-upload'
      preLoaderRoute: typeof AppFiscalNotaFiscalUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/nota-fiscal-importacao': {
      id: '/_app/fiscal/nota-fiscal-importacao'
      path: '/fiscal/nota-fiscal-importacao'
      fullPath: '/fiscal/nota-fiscal-importacao'
      preLoaderRoute: typeof AppFiscalNotaFiscalImportacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/nota-fiscal': {
      id: '/_app/fiscal/nota-fiscal'
      path: '/fiscal/nota-fiscal'
      fullPath: '/fiscal/nota-fiscal'
      preLoaderRoute: typeof AppFiscalNotaFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/impostos': {
      id: '/_app/fiscal/impostos'
      path: '/fiscal/impostos'
      fullPath: '/fiscal/impostos'
      preLoaderRoute: typeof AppFiscalImpostosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/dashboard': {
      id: '/_app/fiscal/dashboard'
      path: '/fiscal/dashboard'
      fullPath: '/fiscal/dashboard'
      preLoaderRoute: typeof AppFiscalDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/cfop': {
      id: '/_app/fiscal/cfop'
      path: '/fiscal/cfop'
      fullPath: '/fiscal/cfop'
      preLoaderRoute: typeof AppFiscalCfopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal/certificados': {
      id: '/_app/fiscal/certificados'
      path: '/fiscal/certificados'
      fullPath: '/fiscal/certificados'
      preLoaderRoute: typeof AppFiscalCertificadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev/cargos': {
      id: '/_app/dev/cargos'
      path: '/dev/cargos'
      fullPath: '/dev/cargos'
      preLoaderRoute: typeof AppDevCargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/industrial': {
      id: '/_app/dashboard/industrial'
      path: '/dashboard/industrial'
      fullPath: '/dashboard/industrial'
      preLoaderRoute: typeof AppDashboardIndustrialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao/op/$id': {
      id: '/_app/producao/op/$id'
      path: '/$id'
      fullPath: '/producao/op/$id'
      preLoaderRoute: typeof AppProducaoOpIdRouteImport
      parentRoute: typeof AppProducaoOpRoute
    }
  }
}

interface AppProducaoOpRouteChildren {
  AppProducaoOpIdRoute: typeof AppProducaoOpIdRoute
}

const AppProducaoOpRouteChildren: AppProducaoOpRouteChildren = {
  AppProducaoOpIdRoute: AppProducaoOpIdRoute,
}

const AppProducaoOpRouteWithChildren = AppProducaoOpRoute._addFileChildren(
  AppProducaoOpRouteChildren,
)

interface AppRouteChildren {
  AppAgulhaRoute: typeof AppAgulhaRoute
  AppArtigosRoute: typeof AppArtigosRoute
  AppClienteArtigoRoute: typeof AppClienteArtigoRoute
  AppComposicaoRoute: typeof AppComposicaoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCorRoute: typeof AppCorRoute
  AppCorreiaRoute: typeof AppCorreiaRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppEstampaRoute: typeof AppEstampaRoute
  AppEstoqueFiosRoute: typeof AppEstoqueFiosRoute
  AppEstoqueTecidosRoute: typeof AppEstoqueTecidosRoute
  AppFioRoute: typeof AppFioRoute
  AppFuncionarioRoute: typeof AppFuncionarioRoute
  AppInicioRoute: typeof AppInicioRoute
  AppLotesRoute: typeof AppLotesRoute
  AppMaquinaRoute: typeof AppMaquinaRoute
  AppMenusRoute: typeof AppMenusRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRepMetaRoute: typeof AppRepMetaRoute
  AppRepresentantesRoute: typeof AppRepresentantesRoute
  AppSenhaRoute: typeof AppSenhaRoute
  AppTabelaCorRoute: typeof AppTabelaCorRoute
  AppTimeLogRoute: typeof AppTimeLogRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVarianteRoute: typeof AppVarianteRoute
  AppDashboardIndustrialRoute: typeof AppDashboardIndustrialRoute
  AppDevCargosRoute: typeof AppDevCargosRoute
  AppFiscalCertificadosRoute: typeof AppFiscalCertificadosRoute
  AppFiscalCfopRoute: typeof AppFiscalCfopRoute
  AppFiscalDashboardRoute: typeof AppFiscalDashboardRoute
  AppFiscalImpostosRoute: typeof AppFiscalImpostosRoute
  AppFiscalNotaFiscalRoute: typeof AppFiscalNotaFiscalRoute
  AppFiscalNotaFiscalImportacaoRoute: typeof AppFiscalNotaFiscalImportacaoRoute
  AppFiscalNotaFiscalUploadRoute: typeof AppFiscalNotaFiscalUploadRoute
  AppFiscalRNotaFiscalRoute: typeof AppFiscalRNotaFiscalRoute
  AppFiscalUfIcmsRoute: typeof AppFiscalUfIcmsRoute
  AppProducaoExpedicaoRoute: typeof AppProducaoExpedicaoRoute
  AppProducaoOpRoute: typeof AppProducaoOpRouteWithChildren
  AppProducaoPedidosRoute: typeof AppProducaoPedidosRoute
  AppProducaoQualidadeRoute: typeof AppProducaoQualidadeRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppProducaoIndexRoute: typeof AppProducaoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgulhaRoute: AppAgulhaRoute,
  AppArtigosRoute: AppArtigosRoute,
  AppClienteArtigoRoute: AppClienteArtigoRoute,
  AppComposicaoRoute: AppComposicaoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCorRoute: AppCorRoute,
  AppCorreiaRoute: AppCorreiaRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppEstampaRoute: AppEstampaRoute,
  AppEstoqueFiosRoute: AppEstoqueFiosRoute,
  AppEstoqueTecidosRoute: AppEstoqueTecidosRoute,
  AppFioRoute: AppFioRoute,
  AppFuncionarioRoute: AppFuncionarioRoute,
  AppInicioRoute: AppInicioRoute,
  AppLotesRoute: AppLotesRoute,
  AppMaquinaRoute: AppMaquinaRoute,
  AppMenusRoute: AppMenusRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRepMetaRoute: AppRepMetaRoute,
  AppRepresentantesRoute: AppRepresentantesRoute,
  AppSenhaRoute: AppSenhaRoute,
  AppTabelaCorRoute: AppTabelaCorRoute,
  AppTimeLogRoute: AppTimeLogRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVarianteRoute: AppVarianteRoute,
  AppDashboardIndustrialRoute: AppDashboardIndustrialRoute,
  AppDevCargosRoute: AppDevCargosRoute,
  AppFiscalCertificadosRoute: AppFiscalCertificadosRoute,
  AppFiscalCfopRoute: AppFiscalCfopRoute,
  AppFiscalDashboardRoute: AppFiscalDashboardRoute,
  AppFiscalImpostosRoute: AppFiscalImpostosRoute,
  AppFiscalNotaFiscalRoute: AppFiscalNotaFiscalRoute,
  AppFiscalNotaFiscalImportacaoRoute: AppFiscalNotaFiscalImportacaoRoute,
  AppFiscalNotaFiscalUploadRoute: AppFiscalNotaFiscalUploadRoute,
  AppFiscalRNotaFiscalRoute: AppFiscalRNotaFiscalRoute,
  AppFiscalUfIcmsRoute: AppFiscalUfIcmsRoute,
  AppProducaoExpedicaoRoute: AppProducaoExpedicaoRoute,
  AppProducaoOpRoute: AppProducaoOpRouteWithChildren,
  AppProducaoPedidosRoute: AppProducaoPedidosRoute,
  AppProducaoQualidadeRoute: AppProducaoQualidadeRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppProducaoIndexRoute: AppProducaoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
