
ALTER TABLE public.tinturarias
  ADD COLUMN IF NOT EXISTS ncm TEXT,
  ADD COLUMN IF NOT EXISTS unidade TEXT,
  ADD COLUMN IF NOT EXISTS preco_custo NUMERIC(14,4),
  ADD COLUMN IF NOT EXISTS preco_venda NUMERIC(14,4),
  ADD COLUMN IF NOT EXISTS estoque_minimo NUMERIC(14,4),
  ADD COLUMN IF NOT EXISTS observacao TEXT;
